"""
explainer.py

LangGraph node that uses Gemini via LangChain
to explain the recommendation generated by
our rule engine.
"""

import os

from dotenv import load_dotenv

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

from state import SunState

# ---------------------------------------------------
# Load Environment Variables
# ---------------------------------------------------

load_dotenv()

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.2
)

# ---------------------------------------------------
# Load System Prompt
# ---------------------------------------------------

with open(
    "prompts/system_prompt.txt",
    "r",
    encoding="utf-8"
) as f:

    SYSTEM_PROMPT = f.read()

# ---------------------------------------------------
# Prompt Template
# ---------------------------------------------------

prompt = ChatPromptTemplate.from_messages(

    [

        ("system", SYSTEM_PROMPT),

        ("human",
         """
City: {city}

Country: {country}

Temperature: {temperature}

UV Index: {uv_index}

Heatstroke Risk: {heatstroke_risk}

Sunburn Risk: {sunburn_risk}

Vitamin D Opportunity:
{vitamin_d_score}

Recommended Duration:
{recommended_duration} minutes

Best Time:
{best_time}
""")

    ]

)

chain = prompt | llm


# ---------------------------------------------------
# LangGraph Node
# ---------------------------------------------------

def explainer_node(state: SunState) -> SunState:

    print("\nExplainer Node Running...")

    response = chain.invoke({

        "city": state["city"],

        "country": state["country"],

        "temperature": state["temperature"],

        "uv_index": state["uv_index"],

        "heatstroke_risk": state["heatstroke_risk"],

        "sunburn_risk": state["sunburn_risk"],

        "vitamin_d_score": state["vitamin_d_score"],

        "recommended_duration":
            state["recommended_duration"],

        "best_time":
            state["best_time"]

    })

    explanation = response.content
    if not isinstance(explanation, str):
        explanation = str(explanation)

    state["explanation"] = explanation

    return state